ru_text_for_images:
  - Что-то мяукнуть очень хочется.
  - Сейчас как мяукну!
  - Мрррр-мррр-прррррррррррррррр, ты так не можешь.
  - Гав, ой, тьфу ты, мяууу!
  - Не кот, а кiт.
  - Мяу, кис ми, где мой вискас?
  - Кс-кссс-КЫСССС.
  - Ты сначала лоток мой почисть.
  - Миу-миу-мв-мяяв-МЭЭЭВ!!!
  - Meow, meow
  - Мяу, мяу
  - Мяу, мяу, мяуууу
  - Котики-бомботики
  - Вот это котяраааа
  - Мууууууууууур
  - Мур Мур мур
  - КОТ-звезда
  - Котопес, нафиг
  - Ты только посмотри
  - Вот это да !
  - Это тебе
  - Совпадение? Не думаю
  - ААААААА, то есть МЯЯААААУУУУУУ!
  - Вот это КОТИЩЕ, твою мурку!
  - Это, случайно, не Борис из вискаса?
  - Кто сказал мяу?
  - Мяу, Мяу. Мяу Мяу Мяу, Мяу. Твой Котик.
  - Почеши мне за ушком, муур
  - Ну почеши, ну мууур, нуууу
  - Что-то так спать хочется... хммм... странно, ведь я даже не просыпался
  - Сметанки бы сейчас ...
  - Я у хозяев не приемный, а РОДНОЙ
  - Играя с кошкой не жалуйтесь на царапины!!!
  - "*ТРЕТСЯ РАДОСТНЫЙ ОБ НОГИ*"

text_for_images:
  - Let's meow as hard as we can!
  - Now I can more meow that before:)
  - I'm in purring trance.
  - Meow or whatever's?
  - MEOOOOWWWWW
  - I'm not a kitty but not yet growth :(
  - Can you cleaning my toilet, human? THANKS:)
  - Pussy-pussy-pussy or how to calling my human now?
  - Meow it's mean universe language and communicate.
  - Cat Around
  - Meow, meow
  - “That’s the great secret of creativity. You treat ideas like cats: you make them follow you.” Ray Bradbury
  - “My relationships with my cats has saved me from a deadly, pervasive ignorance.” William S. Burroughs
  - “Cats choose us; we don’t own them.” Kristin Cast
  - “I love cats because I enjoy my home; and little by little, they become its visible soul.” Jean Cocteau
  - “Time spent with a cat is never wasted.” Colette
  - “Making movies is like herding cats.” Eric Fellner
  - “How we behave toward cats here below determines our status in heaven.” Robert A. Heinlein
  - “I have studied many philosophers and many cats. The wisdom of cats is infinitely superior.” Hippolyte Taine
  - “I wish I could write as mysterious as a cat.” Edgar Allan Poe