ru_text_for_images:
  - Что-то мяукнуть очень хочется.
  - Сейчас как мяукну!
  - Мрррр-мррр-прррррррррррррррр, ты так не можешь.
  - Гав, ой, тьфу ты, мяууу!
  - Не кот, а кiт.
  - Мяу, кис ми, где мой вискас?
  - Кс-кссс-КЫСССС.
  - Ты сначала лоток мой почисть.
  - Миу-миу-мв-мяяв-МЭЭЭВ!!!
  - Meow, meow
  - Мяу, мяу
  - Мяу, мяу, мяуууу
  - Котики-бомботики
  - Вот это котяраааа
  - Мууууууууууур
  - Мур Мур мур
  - КОТ-звезда
  - Котопес, нафиг
  - Ты только посмотри
  - Вот это да !
  - Это тебе
  - Совпадение? Не думаю
  - ААААААА, то есть МЯЯААААУУУУУУ!
  - Вот это КОТИЩЕ, твою мурку!
  - Это, случайно, не Борис из вискаса?
  - Кто сказал мяу?
  - Мяу, Мяу. Мяу Мяу Мяу, Мяу. Твой Котик.
  - Почеши мне за ушком, муур
  - Ну почеши, ну мууур, нуууу
  - Что-то так спать хочется... хммм... странно, ведь я даже не просыпался
  - Сметанки бы сейчас ...
  - Я у хозяев не приемный, а РОДНОЙ
  - Играя с кошкой не жалуйтесь на царапины!!!
  - "*ТРЕТСЯ РАДОСТНЫЙ ОБ НОГИ*"

text_for_images:
  - Let's meow as hard as we can!
  - Now I can more meow that before:)
  - I'm in purring trance.
  - Meow or whatever's?
  - I'm not a kitty but not yet growth :(
  - Can you cleaning my toilet, human? THANKS:)
  - Pussy-pussy-pussy or how to calling my human now?
  - Meow it's mean universe language and communicate.
  - Cat Around
  - Meow, meow