text_for_images:
  - Что-то мяукнуть очень хочется.
  - Сейчас как мяукну!
  - Мрррр-мррр-прррррррррррррррр, ты так не можешь.
  - Гав, ой, тьфу ты, мяууу!
  - Не кот, а кiт.
  - Мяу, кис ми, где мой вискас?
  - Кс-кссс-КЫСССС.
  - Ты сначала лоток мой почисть.
  - Миу-миу-мв-мяяв-МЭЭЭВ!!!
  - Meow, meow
  - Мяу, мяу
  - Мяу, мяу, мяуууу
  - Котики-бомботики
  - Вот это котяраааа
  - Мууууууууууур
  - Мур Мур мур
  - КОТ-звезда
  - Котопес, нафиг
  - Ты только посмотри
  - Вот это да !
  - ААААААА, то есть МЯЯААААУУУУУУ!
  - Вот это КОТИЩЕ, твою мурку!
  - Это случайно, не Борис из вискаса?
  - Кто сказал мяу?
  - Мяу, Мяу. Мяу Мяу Мяу, Мяу. Твой Котик.
  - Почеши мне за ушком, муур
  - Ну почеши, ну мууур, нуууу
  - Что-то спать хочется, я ведь только проснулся
  - Сметанки бы сейчас ...
  - Я у хозяев не родной, а приемный.
  - Играя с кошкой не жалуйтесь на царапины!!!
  - "*ТРЕТСЯ РАДОСТНЫЙ ОБ НОГИ*"